version: '3'
services:
    mydogchase:
        container_name: mydogchase
        build: .
        volumes:
            - .:/opt/src
        ports:
            - "2013:8000"
        command: bash -c "cd /opt/src && cargo run"
        restart: always
